{{- $data := include "kubemg.secretData" . | fromYaml -}}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubemg.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubemg.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
