// Package agentpkg renders the Kubernetes manifests that install a KubeMG Dumb
// Agent into a target cluster.
//
// The manifests are the Kustomize package under base/, embedded into the server
// binary so an installation command never depends on a reachable Git host. That
// directory is a byte-for-byte copy of deploy/kustomize/base/, which is the
// human-facing one; `make manifest-check` fails the build if they drift.
package agentpkg

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"embed"
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"
)

//go:embed base/*.yaml
var baseFS embed.FS

// Defaults applied when the server is not configured otherwise.
const (
	DefaultNamespace = "kubemg-system"
	DefaultImage     = "docker.io/ozkanpoyrazoglu/kubemg-agent:0.1.0"
	// PackageDir is the directory name inside the rendered archive. It is also
	// what the operator types after `kubectl apply -k`.
	PackageDir = "kubemg-agent"
)

// Placeholders substituted when rendering. They are deliberately loud so an
// unrendered manifest fails obviously rather than installing a broken agent.
const (
	placeholderNamespace = "__AGENT_NAMESPACE__"
	placeholderBastion   = "__BASTION_URL__"
	placeholderToken     = "__CLUSTER_TOKEN__"
	placeholderImage     = "__AGENT_IMAGE__"
)

// applyOrder is the order resources are concatenated into the flat manifest.
// Kustomize sorts for itself, but `kubectl apply -f` does not: the namespace
// has to exist before anything lands in it, and the Secret before the
// Deployment that mounts it.
var applyOrder = []string{
	"namespace.yaml",
	"rbac.yaml",
	"secret.yaml",
	"deployment.yaml",
	"kustomization.yaml",
}

// Options are the per-cluster values baked into a rendered package.
type Options struct {
	// BastionURL is the public base URL of this KubeMG server, the address the
	// agent dials out to.
	BastionURL string
	// ClusterToken is the cluster's registration secret.
	ClusterToken string
	// Namespace and Image fall back to the defaults above when empty.
	Namespace string
	Image     string
}

func (o Options) normalize() (Options, error) {
	if strings.TrimSpace(o.BastionURL) == "" {
		return o, fmt.Errorf("bastion URL is required to render an agent package")
	}
	if strings.TrimSpace(o.ClusterToken) == "" {
		return o, fmt.Errorf("cluster registration token is required to render an agent package")
	}
	o.BastionURL = strings.TrimRight(strings.TrimSpace(o.BastionURL), "/")
	o.ClusterToken = strings.TrimSpace(o.ClusterToken)
	if o.Namespace == "" {
		o.Namespace = DefaultNamespace
	}
	if o.Image == "" {
		o.Image = DefaultImage
	}
	return o, nil
}

// Render fills the package in for one cluster, returning file name -> content.
// Values are quoted where they land in YAML scalars, so a URL containing a
// colon cannot break the document.
func Render(opts Options) (map[string]string, error) {
	opts, err := opts.normalize()
	if err != nil {
		return nil, err
	}

	entries, err := fs.ReadDir(baseFS, "base")
	if err != nil {
		return nil, fmt.Errorf("read embedded agent package: %w", err)
	}

	replacer := strings.NewReplacer(
		placeholderNamespace, opts.Namespace,
		placeholderBastion, quote(opts.BastionURL),
		placeholderToken, quote(opts.ClusterToken),
		placeholderImage, quote(opts.Image),
	)

	out := make(map[string]string, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		raw, err := fs.ReadFile(baseFS, path.Join("base", entry.Name()))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", entry.Name(), err)
		}
		out[entry.Name()] = replacer.Replace(string(raw))
	}
	return out, nil
}

// Manifest renders the package as one apply-able YAML stream. This is what
// `kubectl apply -f <url>` consumes, so the kustomization itself is left out —
// it is not a Kubernetes object.
func Manifest(opts Options) (string, error) {
	files, err := Render(opts)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	buf.WriteString("# KubeMG Dumb Agent\n")
	buf.WriteString("# Generated by the KubeMG bastion. Contains this cluster's registration\n")
	buf.WriteString("# token: treat it like a credential.\n")

	for _, name := range fileOrder(files) {
		if name == "kustomization.yaml" {
			continue
		}
		buf.WriteString("---\n")
		buf.WriteString(strings.TrimRight(files[name], "\n"))
		buf.WriteString("\n")
	}
	return buf.String(), nil
}

// Archive renders the package as a gzipped tarball rooted at PackageDir, ready
// to extract and hand to `kubectl apply -k`.
func Archive(opts Options) ([]byte, error) {
	files, err := Render(opts)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)

	for _, name := range fileOrder(files) {
		body := []byte(files[name])
		header := &tar.Header{
			Name: path.Join(PackageDir, name),
			Mode: 0o600,
			Size: int64(len(body)),
		}
		if err := tw.WriteHeader(header); err != nil {
			return nil, fmt.Errorf("write archive header for %s: %w", name, err)
		}
		if _, err := tw.Write(body); err != nil {
			return nil, fmt.Errorf("write archive entry for %s: %w", name, err)
		}
	}

	if err := tw.Close(); err != nil {
		return nil, fmt.Errorf("close tar: %w", err)
	}
	if err := gz.Close(); err != nil {
		return nil, fmt.Errorf("close gzip: %w", err)
	}
	return buf.Bytes(), nil
}

// fileOrder puts the known files in apply order and appends anything else
// alphabetically, so adding a manifest to base/ cannot silently drop it.
func fileOrder(files map[string]string) []string {
	out := make([]string, 0, len(files))
	seen := map[string]bool{}
	for _, name := range applyOrder {
		if _, ok := files[name]; ok {
			out = append(out, name)
			seen[name] = true
		}
	}

	rest := []string{}
	for name := range files {
		if !seen[name] {
			rest = append(rest, name)
		}
	}
	sort.Strings(rest)
	return append(out, rest...)
}

// quote renders a value as a double-quoted YAML scalar.
func quote(value string) string {
	escaped := strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value)
	return `"` + escaped + `"`
}
